#!/usr/bin/env python3

import rospy
import time
from std_msgs.msg import Float32MultiArray, Float32

if __name__ == "__main__":
    rospy.init_node('motor_qik_test_node')
    pub = rospy.Publisher("/command", Float32MultiArray, queue_size = 1)
    for i in range(100):
      if rospy.is_shutdown():
          break
      m = Float32MultiArray()
      m.data = [i/100., i/100.] * 2
      pub.publish(m)
      print(m)
      time.sleep(0.1)

    for i in reversed(range(100)):
      if rospy.is_shutdown():
          break
      m = Float32MultiArray()
      m.data = [i/100., i/100.] * 2
      pub.publish(m)
      print(m)
      time.sleep(0.1)
