#!/usr/bin/env python3

import json
import psutil
import rospy
import time

from std_msgs.msg import String

if __name__ == "__main__":
    rospy.init_node("psutil_node")

    pub_psutil = rospy.Publisher("psutil", String, queue_size = 1)

    rate = rospy.Rate(0.2)
    while not rospy.is_shutdown():
        rate.sleep()

        status = {}

        sensors_temperatures = psutil.sensors_temperatures()
        status["temp"] = {}
        for key in sensors_temperatures:
            status["temp"][key] = dict(list(map(lambda x:(x.label, x.current),
                sensors_temperatures[key])))

        disk_usage = psutil.disk_usage('/')
        status["disk"] = {
          "total": disk_usage.total,
          "used": disk_usage.used,
          "free": disk_usage.free,
          "percent": disk_usage.percent,
        }

        status["cpu"] = psutil.cpu_percent(percpu=True)

        net_io_counters = psutil.net_io_counters()
        status["net"] = {
          "bytes_sent": net_io_counters.bytes_sent,
          "bytes_recv": net_io_counters.bytes_recv,
          "packets_sent": net_io_counters.packets_sent,
          "packets_recv": net_io_counters.packets_recv,
        }

        status["mem"] = {
          "virtual": psutil.virtual_memory().percent,
          "swap": psutil.swap_memory().percent,
        }

        pub_psutil.publish(json.dumps(status))

