#!/usr/bin/env python3

import serial
import time

ser = serial.Serial("/dev/ttyUSB0", baudrate=115200)

for i in range(100):
  print(i)
  cmd = (bytes([0xF0]) + b'G' + bytes([0]) + bytes([i >> 8, i & 0xFF]))
  print(cmd)
  ser.write(cmd)
  ser.flush()
  time.sleep(0.01)
for i in reversed(range(100)):
  print(i)
  cmd = (bytes([0xF0]) + b'G' + bytes([0]) + bytes([i >> 8, i & 0xFF]))
  print(cmd)
  ser.write(cmd)
  ser.flush()
  time.sleep(0.01)

ser.close()
