#!/usr/bin/env python3

import serial
import time

ser = serial.Serial("/dev/ttyUSB0", baudrate=115200)

for i in range(100):
  cmd = bytes([0xF0]) + b'G'
  ser.write(cmd)
  ser.flush()
  time.sleep(0.1)
